import { StyleSheet } from 'react-native'
import { colors } from 'theme'

export default StyleSheet.create({
  // container: {
  //   flex: 1,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  container: {
    flex: 1,
    display: 'flex',
    borderColor: 'black',
    marginBottom: 15,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    width: '90%',
    // height: '90%',
    marginLeft: '5%',
    marginRight: '5%',
    marginTop: '5%',
    height: '1300%',
    // marginBottom: 30,
    backgroundColor: colors.orange,
  },
  flatList: {
    flex: 1,
    marginBottom: 60,
    marginTop: 20,
  },
  phaseContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 12,
  },
  flexLeftInner1: {
    backgroundColor: 'white',
    borderRadius: 15,

    // width: '90%',
    // margin: 15,
    padding: 30,
    flex: 1,
  },
  header: {
    marginTop: 10,
    fontSize: 30,
    marginBottom: 0,
    padding: 0,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 10,
    textAlign: 'center',
  },
  h1: {
    fontSize: 30,
    padding: 20,
    paddingBottom: 10,
    textAlign: 'center',
  },
  emoji: {},
  input: {
    // marginHorizontal: 30,
    // marginVertical: 40,
    // textAlign: 'justify',
    // fontFamily: "sans-serif-light",
    fontSize: 16,
    // backgroundColor:
  },
  textBox: {
    marginTop: 10,
    marginBottom: 10,
    height: 300,
    borderRadius: 15,
    borderWidth: 10,
    borderColor: '#F5F5F5',
    backgroundColor: '#F5F5F5',
  },
  darktitle: {
    fontSize: 24,
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 10,
    textAlign: 'center',
    color: 'white',
  },
  field: {
    fontSize: 15,
    marginBottom: 5,
    marginLeft: 10,
    textAlign: 'center',
  },
  darkfield: {
    fontSize: 15,
    marginBottom: 5,
    marginLeft: 10,
    color: 'white',
    textAlign: 'center',
  },
  main: {
    flex: 1,
    width: '100%',
  },
  text: {
    fontSize: 18,
    textAlign: 'center',
    color: '#656565',
  },
  journalText: {
    textAlign: 'center',
    margin: 40,
  },
  customButton: {
    display: 'flex',
    marginTop: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 40,
    alignItems: 'center',
    backgroundColor: '#1c9ab7',
    borderRadius: 10,
    padding: 10,
  },
  linebreak: {
    borderBottomColor: colors.gray,
    borderBottomWidth: 1,
    marginVertical: 30,
    alignSelf: 'center',
    width: '85%',
    // flex:1
  },
})
